services:
  client:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
      - "9229"
    ports:
      - "3000:3000"
      - "9229:9229"
    command: "npx lerna run --scope @chopped/client --stream start"
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3001"
      - "9339"
    ports:
      - "3001:3001"
      - "9339:9339"
    command: "npx lerna run --scope @chopped/server --stream start"
