name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npx lerna run test --stream
          npx lerna run build --stream
        env:
          CI: true
          NODE_OPTIONS: '--trace-warnings'
